version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: mozart/grails
    steps:
      - checkout
      - run : export GRAILS_OPTS="-XX:-UseSplitVerifier -Xverify:none"
      - run: grails --version
      - run: pwd
      - run: grails create-app myApp
